### PR TITLE
Custom terminal title for Bottom

### PR DESCRIPTION
**Pull request by RaresCon**
## Description

_A description of the change, what it does, and why it was made. If relevant (such as any change that modifies the UI), **please provide screenshots** of the changes:_

Added an option to change the terminal name. The user can use `--title`, followed by the desired name for the terminal, or use `title_to_hostname` field (true/false) in the config file to force the name of the terminal to be the name of the host machine. Otherwise, if no option is used, the default name of the terminal will be now "Bottom". It also works while using SSH.

Windows example

WSL/Ubuntu example

Arch example

Option example

Hostname example

## Issue

_If applicable, what issue does this address?_

#https://github.com/ClementTsang/bottom/issues/277

## Testing

_If relevant, please state how this was tested. All changes **must** be tested to work:_

Tested it on multiple platforms. I also used SSH on all of them.

_If this is a code change, please also indicate which platforms were tested:_

- [x] _Windows_
- [x] _macOS_
- [x] _Linux_

## Checklist

_If relevant, ensure the following have been met:_

- [x] _Areas your change affects have been linted using rustfmt (`cargo fmt`)_
- [x] _The change has been tested and doesn't appear to cause any unintended breakage_
- [x] _Documentation has been added/updated if needed (`README.md`, help menu, doc pages, etc.)_
- [ ] _The pull request passes the provided CI pipeline_
- [x] _There are no merge conflicts_
- [ ] _If relevant, new tests were added (don't worry too much about coverage)_

### CODE REVIEW

**Comment by alexandruradovici** [comment]
It builds on macOS, but does not seem to change the title. Might be a macOS problem.

Tried on a different terminal app, it works.

**Comment by RaresCon** [comment]
I will test it on macOS as well. Is the rebase needed for the Cargo.toml that has conflicts with master? If so, I added a new crate, `gethostname`, which is used to get the hostname.

**Comment by alexandruradovici** [comment]
> I will test it on macOS as well. Is the rebase needed for the Cargo.toml that has conflicts with master? If so, I added a new crate, `gethostname`, which is used to get the hostname.

Yes, due to Cargo.toml.

**Comment by RaresCon** [comment]
Done, there are no more conflicts.

**Comment by alexandruradovici** [comment]
Send the pull request and post a link to it.

**Comment by RaresCon** [comment]
https://github.com/ClementTsang/bottom/pull/999/

**Pull request closed without merging**
