### PR TITLE
Added possibility to use "--memory_use_mega_prefix"

### PR DESCRIPTION
**Pull request by GrecuAlexandru**
## Description

Added possibility to use "--memory_use_mega_prefix" flag to see the RAM memory in MiB even if it exceeds 1 GiB.

## Issue

Added the request provided here: https://github.com/ClementTsang/bottom/discussions/695 and https://github.com/ClementTsang/bottom/issues/696

### CODE REVIEW

**Comment by alexandruradovici** [comment]
Please fix the formatting issue.

**Comment by alexandruradovici** [comment]
Please run `cargo fmt` locally.

**Comment by alexandruradovici** [comment]
Looks good, please open a pull request to upstream and paste a link to the pull request here.

**Comment by alexandruradovici** [comment]
Please rebase this from `master`.

**Comment by GrecuAlexandru** [comment]
https://github.com/ClementTsang/bottom/pull/1375

**Pull request closed without merging**
